[package]
name = "file-chest"
version = "0.0.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# gtk = { version = "0.5.5", package = "gtk4" }
iced = "0.7.0"
iced_lazy = "0.4.0"
iced_native = "0.8.0"
